### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by aaemnnosttv** [djdesign/valet-roots#1]
Hey there, thanks for the kind words.

I took a look over your script and there are a few things you could change if you wanted.
## 

```
# set db name
dbname=wp_$sitename
```

This is unnecessary as it is the default used by the valet command.
## 

```
wp dotenv salts regenerate --file=.env
```
- .env is also the default for `file` so you can leave that off as well.
- You could also use this as just `generate` now as it will replace salts now if they are placeholder values.
## 

```
# discourage search engines
wp option update blog_public 0
```

This is unnecessary as Bedrock does this for you with an mu-plugin automatically based on `WP_ENV`, but probably not a concern for local dev anyways.
## 

```
# set pretty urls
wp rewrite structure '/%postname%/' --hard
wp rewrite flush --hard
```

No need to use `--hard` here as these trigger updating a `.htaccess` file and thus are Apache-specific.
## 

```
wp login install --activate
```

This will install the plugin but if you want it to be part of the project, you can require it with composer: 

```
wp login install --activate
composer require aaemnnosttv/wp-cli-login-server --no-update # add to composer.json but skip install since it is already there.
```

You could alternatively skip the `login install`, and require the package without `--no-update` and then `wp login toggle on` to activate it. It would take longer, but your `composer.lock` would be in sync w/ the `composer.json`.
## 

```
wp theme delete twentyfifteen twentyfourteen twentythirteen twentytwelve twentyeleven twentyten
```

If you don't want these showing up under Appearance > Themes, you just need to [define `WP_DEFAULT_THEME`](https://github.com/roots/bedrock/blob/master/web/app/mu-plugins/register-theme-directory.php#L12).  These are contained within WP core, so they will just be reinstalled again as soon as WP is updated or with a fresh `composer install`.

**Comment by dwillitzer** [comment]
@aaemnnosttv Thank you for the feed back. Tested and applied your suggestions.
